# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-11 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aktas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('istaiga', models.CharField(max_length=200)),
                ('data', models.DateTimeField(verbose_name='date published')),
                ('istatymo_nr', models.IntegerField()),
                ('direktorius', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mat_Vertybe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vertybe_nr', models.IntegerField()),
                ('pavadinimas', models.CharField(max_length=200)),
                ('vnt', models.CharField(max_length=200)),
                ('kiekis', models.IntegerField()),
                ('suma', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Narys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vardas', models.CharField(max_length=200)),
                ('pavarde', models.CharField(max_length=200)),
                ('pareigos', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pirkimo_Dokumentas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pardavejas', models.CharField(max_length=200)),
                ('serija', models.CharField(max_length=200)),
                ('numeris', models.IntegerField()),
                ('pirkimo_data', models.DateTimeField(verbose_name='pirkimo data')),
            ],
        ),
        migrations.CreateModel(
            name='Vieta1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tikslas', models.CharField(max_length=200)),
                ('vertybe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Mat_Vertybe')),
            ],
        ),
        migrations.RemoveField(
            model_name='vertybe',
            name='vieta',
        ),
        migrations.DeleteModel(
            name='Vertybe',
        ),
        migrations.DeleteModel(
            name='Vieta',
        ),
        migrations.AddField(
            model_name='aktas',
            name='narys',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Narys'),
        ),
        migrations.AddField(
            model_name='aktas',
            name='pirkimo_dokumentas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Pirkimo_Dokumentas'),
        ),
        migrations.AddField(
            model_name='aktas',
            name='vieta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Vieta1'),
        ),
    ]
