# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-12 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20170512_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktas',
            name='pavadinimas',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
