# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-12 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20170512_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vieta',
            old_name='tikslas',
            new_name='padalinys',
        ),
        migrations.AddField(
            model_name='vertybe',
            name='tikslas',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
