# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20170512_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='narys',
            name='pareigos',
            field=models.CharField(choices=[('PR', 'Komisijos pirmininkas'), ('NR', 'Narys')], max_length=200),
        ),
    ]
