# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20170514_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktas',
            name='pirmininkas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Narys'),
        ),
        migrations.AlterField(
            model_name='aktas',
            name='nariai',
            field=models.ManyToManyField(blank=True, related_name='Narys', to='polls.Narys'),
        ),
    ]
