# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20170514_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='vieta',
            name='naudotojas',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
