# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_vieta_naudotojas'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktas',
            name='menesis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aktas',
            name='metai',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
